# Generated by Django 2.0 on 2019-03-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('card_text', models.TextField(blank=True, null=True)),
                ('point_value', models.CharField(blank=True, max_length=3, null=True)),
                ('anti_ship_lng_dice', models.IntegerField(blank=True, null=True)),
                ('anti_ship_med_dice', models.IntegerField(blank=True, null=True)),
                ('anti_ship_cls_dice', models.IntegerField(blank=True, null=True)),
                ('unique', models.BooleanField(default=False)),
                ('faction', models.CharField(blank=True, max_length=9, null=True)),
                ('upgrade_type', models.CharField(blank=True, max_length=200, null=True)),
                ('modification', models.BooleanField(default=False)),
                ('ship_size', models.CharField(blank=True, max_length=200, null=True)),
                ('flotilla', models.BooleanField(default=False)),
                ('bomber', models.BooleanField(default=False)),
                ('objective_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_amounts', to='ddfleetapp.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admiral_name', models.CharField(max_length=200)),
                ('faction', models.CharField(choices=[('Imperial', 'Imperial'), ('Rebel', 'Rebel')], default='Rebel', max_length=9)),
                ('list_name', models.CharField(max_length=200)),
                ('point_total', models.IntegerField(default=0)),
                ('cards', models.ManyToManyField(related_name='fleets', through='ddfleetapp.CardAmount', to='ddfleetapp.Card')),
            ],
        ),
        migrations.AddField(
            model_name='cardamount',
            name='fleet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_amounts', to='ddfleetapp.Fleet'),
        ),
    ]
