# Generated by Django 2.0 on 2019-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddfleetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='point_value',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
