# Generated by Django 2.0 on 2019-03-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddfleetapp', '0002_auto_20190319_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
